### ISSUE TITLE
Bare domain won't resolve

### ISSUE THREAD

**Issue by weex** [pubky/pkdns#12]
Tried visiting - [http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/](http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/) from Firefox and Chromium but the browser wants to add .home and .lan respectively.

[http://pknames.p2p.7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/](http://pknames.p2p.7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/) did work from both however so I'm proposing to put that URL first in the docs.

**Comment by affektde** [comment]
I tried it on Windows, too. Set a custom DNS to my Proton VPN settings.

But It works only if you add a `.` at the end of the domain:

`http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy./`

The subdomain http://pknames.p2p.7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/ works also for me.

I tried to add the explicit absolute domain root to my A entry, But no change. Still need `.` at the end of the root domain on Windows.

On Linux everything is fine.

**Comment by HolgerHatGarKeineNode** [comment]
> I tried it on Windows, too. Set a custom DNS to my Proton VPN settings.
> 
> But It works only if you add a `.` at the end of the domain:
> 
> `http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy./`
> 
> The subdomain http://pknames.p2p.7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy/ works also for me.
> 
> I tried to add the explicit absolute domain root to my A entry, But no change. Still need `.` at the end of the root domain on Windows.
> 
> On Linux everything is fine.

I can confirm this on my Windows VM. Browsers only open `http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy./` on Windows.

**Comment by SeverinAlexB** [comment]
Browser resolution is tricky. [http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy./](http://7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy./) feels like the best way forward to make it compatible. @weex this should work for you too, doesn't it?

**Comment by SeverinAlexB** [comment]
Merged the fix. Closing this. Let me know if you have any other issues.
