### ISSUE TITLE
DHT connectivity lost/unclear

### ISSUE THREAD

**Issue by weex** [pubky/pkdns#14]
Had pkdns running for a few hours, then published a record using a fresh key from another location on the internet, but pkdns didn't provide an answer within ~5 minutes. So I restarted pkdns, gave it a minute and then it was able to resolve the query successfully.

I'm running pkdns with -v for verbose mode but don't see any messages on DHT status. It would be great to surface some info like DHT connection health every so often.

**Comment by SeverinAlexB** [comment]
#31 adds a logging doc. Running `RUST_LOG=pkdns=debug,any_dns=debug,pkarr=debug,mainline=debug pkdns` will output the mainline logs. 

The mainline DHT uses UDP and not TCP and is therefore connectionless so you will not see any connection info. Nonetheless logs like `DEBUG mainline::rpc: Populated the routing table table_size=108` show how many other DHT nodes pkdns knows about. It's a great indication if everything is working.

**Comment by weex** [comment]
That should help. Closing for now but will reopen if it still happens. Thanks!
