### ISSUE TITLE
Fix Local Path Issue for `any-dns` Dependency

### ISSUE THREAD

**Issue by vforvilela** [pubky/pkdns#32]
The `any-dns` dependency in `Cargo.toml` is currently pointing to a local path:  
[https://github.com/pubky/pkdns/blob/master/server/Cargo.toml#L16](https://github.com/pubky/pkdns/blob/master/server/Cargo.toml#L16)

```toml
# any-dns = "0.3.1"
any-dns = {path = "/Users/severinbuhler/git/pknames/any-dns"}
``` 

I tried replacing it with `any-dns = "0.3.1"`, and it compiles fine. However, I’m not sure if it will work in every situation or if a modified version is needed.

Could someone clarify or make adjustments to ensure it works universally?

Thanks!

**Comment by SeverinAlexB** [comment]
That's my bad, a development artifact. Fixed.
