### ISSUE TITLE
Hosted DNS server(s) mentionned in servers.txt down

### ISSUE THREAD

**Issue by benichu** [pubky/pkdns#5]
Trying this IP `34.65.132.219`: from https://github.com/pubky/pkdns/blob/master/servers.txt
These commands are not working
- `nslookup 7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy 34.65.132.219`
- `ping 34.65.132.219`

Is the server up and running?

**Comment by SeverinAlexB** [comment]
My bad. Updated servers.txt with the new IP `37.27.13.182`.

```
➜  ~  nslookup 7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy 37.27.13.182 
Server:		37.27.13.182
Address:	37.27.13.182#53

Non-authoritative answer:
Name:	7fmjpcuuzf54hw18bsgi3zihzyh4awseeuq5tmojefaezjbd64cy
Address: 34.65.119.29
```

**Comment by benichu** [comment]
Thanks a lot!

So that I understand, does this test server has a fallback DNS server set? (doesn't look like it does)

**Comment by benichu** [comment]
In any case, thanks for the great work, I am gonna install a self hosted server ASAP. 
And try the rest of the pubky stack, it looks like it might be exactly what I need for an upcoming project :)
