### ISSUE TITLE
Failed to parse the seed file. not a zbase32 digit 

### ISSUE THREAD

**Issue by benichu** [pubky/pkdns#6]
I followed this instructions: https://github.com/pubky/pkdns?tab=readme-ov-file#announce-your-own-records and generate a seed with `./pkdns-cli generate > seed.txt`

Then when I try to publish a zone with the previously generated seed, I get the error message (for example): `Failed to parse the seed file. not a zbase32 digit mye4rjq13748hcktxa8ordj5impwk3jpkocn9ah7yjkix8g1nquy`

Tried with `master` and with the `v0.0.5` linux package

**Comment by SeverinAlexB** [comment]
Did you use `./pkdns-cli generate > seed.txt` exactly or did you write the seed another way into the `seed.txt`? For example, this can happen if you  run `./pkdns-cli generate` first, copy the seed and then write it into `seed.txt`via a file editor (nano, vi). The editor adds a newline to the seed file which then leads to the `not a zbase32 digit` error.

I probably should trim the seed.txt to prevent this error 🤔

**Comment by SeverinAlexB** [comment]
New release available https://github.com/pubky/pkdns/releases/tag/v0.5.1

**Comment by benichu** [comment]
I tried directly from your latest master, trimming did the job!

Thanks a lot.

**Comment by benichu** [comment]
> Did you use `./pkdns-cli generate > seed.txt` exactly or did you write the seed another way into the `seed.txt`? For example, this can happen if you run `./pkdns-cli generate` first, copy the seed and then write it into `seed.txt`via a file editor (nano, vi). The editor adds a newline to the seed file which then leads to the `not a zbase32 digit` error.
> 
> I probably should trim the seed.txt to prevent this error 🤔

FWIW I was using the CLI, not writing the seed with an editor

**Comment by SeverinAlexB** [comment]
Glad it works now.
