### ISSUE TITLE
No DHT resolution

### ISSUE THREAD

**Issue by weex** [pubky/pkdns#9]
I set this up and got it running, but it doesn't seem to resolve anything from the mainline DHT. Is there another service it's expecting to find? A high-level checklist on how to setup the stack would be very helpful.

**Comment by SeverinAlexB** [comment]
Hi weex

If you like to setup pkdns, the main [README.md](https://github.com/pubky/pkdns/blob/master/README.md) should guide you through the first steps + allow you to publish your first public key domain.

If you want more information about Pubky, I recommend you checkout [pubky.org](https://pubky.org/#get-started) and the related [knowledge base](https://docs.pubky.org/).

If you got any more questions, feel free to ask them in the Pubky Telegram group.

**Comment by weex** [comment]
I suspect pkdns cannot forward requests for itself. It started resolving DHT info once I created records in /etc/hosts for a few of the bittorrent domains. I also had to include a -s flag to tell it to listen on the public ip of my cloud server.
